### ISSUE TITLE
Détailler les champs Outputs des API

### ISSUE THREAD

**Issue by frntn** [DeveloperLaPoste/okapi-feedback#1]
Pour la ressource `/controladresse/v1/adresses/{code}` on peut lire dans la doc : 

> Le code d’adresse est un identifiant temporaire obtenu via la ressource `/controladresse/v1/adresses{?q}`.

Mais la documentation de la ressource `/controladresse/v1/adresses{?q}` ne mentionne rien au sujet de ce champ : son caractère temporaire, sa durée de validité, ...

Il serait donc intéressant d'avoir, pour toutes les ressources, les spécifications de chaque champ renvoyé dans le JSON de réponse. Par exemple :

- Description
- Longueur Max
- Type
- ...

**Comment by openhoat** [comment]
Tout à fait, c'est à cela que servent les schémas JSON qui peuvent (doivent) figurer dans la documentation pour augmenter sa qualité.
Je vais remonter à nouveau le point au métier, car c'est à eux qu'il incombe de spécifier ces assets, donc je laisse ouvert ce ticket.
Merci
