### ISSUE TITLE
Ancres HTML dans les pages de doc

### ISSUE THREAD

**Issue by frntn** [DeveloperLaPoste/okapi-feedback#2]
La documentation d'une API donnée est contenue sur une seule page HTML ce qui est très pratique !

En revanche, pour pouvoir linker plus finement ( lors des créations de tickets par exemple ) il serait intéressant d'avoir des ancres sur les différentes sections de la page (ressources, requetes, reponses, ...)

**Comment by openhoat** [comment]
J'ai signalé ce point, le problème est partagé.
Nous sommes en train d'y travailler, cela peut paraître trivial mais dans le contexte PWA + react en réalité l'implémentation est plus complexe.
On devrait pouvoir corriger très prochainement, je laisse ouvert ce ticket.
