### ISSUE TITLE
Nommage API

### ISSUE THREAD

**Issue by frntn** [DeveloperLaPoste/okapi-feedback#3]
Le nom de l'API `ControlAdresse` est un mix EN _(Control)_ et FR _(Adresse)_ 
Par souci de cohérence il me semble qu'il faudrait rationnaliser :

- soit en EN avec `ControlAddress`
- soit en FR avec `ControleAdresse`

Evidemment pour **La Poste** par souci de souveraineté, tout passer en FR serait plus logique.

---

_J'avoue que c'est du détail et que ça peu paraitre excessif :smile:
Il me semblait malgré tout utile de le remonter_

**Comment by openhoat** [comment]
Nous avions signalé ce problème dés le début et donner notre avis en tant que plateforme open API (on fait systématiquement un mini audit avant raccordement)
Mais le métier a souhaité maintenir ce nom, donc considérant que le nom du produit est un nom propre nous avons respecté leur choix.
Nous sommes en phase sur l'analyse, mais malheureusement il s'agit d'un problème de souveraineté du métier.
Néanmoins, l'avoir formalisé ici va peut-être nous aider à terme à revenir sur ce vilain nommage, donc merci.
